### ISSUE TITLE
new tabs opened via "open link" don't survive session restore

### ISSUE THREAD

**Issue by kodos96** [ngdeleito/easyGestures#6] opened 2016-08-26 20:51 UTC
Hi,
I noticed an odd bug/incompatibility with current Firefox - any tabs opened via easyGestures' "open link" command fail to get restored properly after a crash or restart of the browser: the tabs come up, but they have empty content and are just labeled "new tab". 

Thanks for maintaining this extension!

**Comment by ngdeleito** [comment] 2016-08-28 17:57
Hi,

Thanks for reporting!

I have to say that I have observed some issues with opening and closing tabs with Firefox Developer Edition, but not with the release version of Firefox (48.0.1 at this moment). I cannot reproduce at this moment the issue you describe in Firefox 48.0.1. I guess you are using this version?

**Comment by kodos96** [comment] 2016-08-29 18:13
Hmm, apparently I was using an older version of firefox without realizing it, as auto-updates had stopped at some point for some reason. After manually upgrading to 48.0.2, the behavior has stopped, and everything seems to be working. Thanks!

**Comment by ngdeleito** [comment] 2016-08-30 17:00
OK, great to hear that!

**Closed by ngdeleito** 2016-08-30 17:00 UTC
